[package]
name = "advent-2020"
version = "0.1.0"
authors = ["Chris Lieb <chris.lieb@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
itertools = "0.9.0"
maplit = "1.0.2"
num = "0.3.1"
regex = "1.4.2"
